// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgn4vo9m9CGkypvDb4hi16kEvB1Ei_7Y',
    appId: '1:317782254077:web:012452ddb597c4aa89b994',
    messagingSenderId: '317782254077',
    projectId: 'indah-flutter',
    authDomain: 'indah-flutter.firebaseapp.com',
    storageBucket: 'indah-flutter.appspot.com',
    measurementId: 'G-BQCEHX2SFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcCfSIiiKU8Df37-GI9mfr1tCP2En7Pgk',
    appId: '1:317782254077:android:e3d1704cd3e1e1e189b994',
    messagingSenderId: '317782254077',
    projectId: 'indah-flutter',
    storageBucket: 'indah-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_dXh8x4A76c5G8vtHHsUvMTc_vPp6YN4',
    appId: '1:317782254077:ios:60987d86e319628689b994',
    messagingSenderId: '317782254077',
    projectId: 'indah-flutter',
    storageBucket: 'indah-flutter.appspot.com',
    iosBundleId: 'com.example.indahFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_dXh8x4A76c5G8vtHHsUvMTc_vPp6YN4',
    appId: '1:317782254077:ios:13a6745788558ed689b994',
    messagingSenderId: '317782254077',
    projectId: 'indah-flutter',
    storageBucket: 'indah-flutter.appspot.com',
    iosBundleId: 'com.example.indahFlutter.RunnerTests',
  );
}
